### ISSUE TITLE
Deserialization problems on read_attributes (EZSP 5)

### ISSUE THREAD

**Issue by rcloran** [rcloran/bellows#19]
Exception:

DEBUG:bellows.ezsp:Application frame 63 (messageSentHandler) received
DEBUG:bellows.uart:Data frame: b'1556b157546f15b658944a24ab5593499c59d8770af29874f8de6782fcbf132d7e'
DEBUG:bellows.uart:Sending: b'82503a7e'
DEBUG:bellows.ezsp:Application frame 69 (incomingMessageHandler) received
ERROR:homeassistant.core:Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
result = next(coro)
File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/zha/__init__.py", line 142, in async_device_initialized
discovered_info = yield from discoverendpoint_info(endpoint)
File "/usr/local/lib/python3.4/dist-packages/homeassistant/components/zha/__init__.py", line 269, in discoverendpoint_info
allow_cache=True,
File "/opt/hass/.homeassistant/deps/bellows/zigbee/zcl/__init__.py", line 183, in read_attributes
for record in result[0]:
TypeError: 'uint8_t' object is not iterable

**Comment by rcloran** [comment]
Right. The frame from the log message encodes a Status.SOFTWARE_FAILURE. Probably the remote device didn't implement all of the attributes or something.

Bellows should probably raise an exception here.
