### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by oakbrad** [rcloran/bellows#30]
Hi I am trying to set this up with Home Assistant 0.47.1 and the Nortek HZUZB1 stick.

When starting HA with zha enabled it hangs. If I run bellows from within the HA virtualenv I get:

```
bellows -d /dev/ttyUSB1 devices
Traceback (most recent call last):
  File "/srv/homeassistant/bin/bellows", line 9, in <module>
    load_entry_point('bellows==0.2.7', 'console_scripts', 'bellows')()
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/homeassistant/lib/python3.4/site-packages/bellows/cli/application.py", line 56, in devices
    app = bellows.zigbee.application.ControllerApplication(ezsp, database)
  File "/srv/homeassistant/lib/python3.4/site-packages/bellows/zigbee/application.py", line 28, in __init__
    self._dblistener = bellows.zigbee.appdb.PersistingListener(database_file, self)
  File "/srv/homeassistant/lib/python3.4/site-packages/bellows/zigbee/appdb.py", line 29, in __init__
    detect_types=sqlite3.PARSE_DECLTYPES)
sqlite3.OperationalError: unable to open database file
```

The zigbee.db file did get created in the appropriate spot for HA and it is owned by the HA user so I don't think it's a permissions issue.

Someone with a similar error here:
https://community.home-assistant.io/t/0-44-zha-config-questions/17295/6

**Comment by rcloran** [comment]
The bellows CLI does not read your Home Assistant config. You can specify the location to the database file with the -D option.

```
$ bellows devices --help
Usage: bellows devices [OPTIONS]

  Show device database

Options:
  -D, --database PATH
  --help               Show this message and exit.
```
